version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: 'Europe/Paris'
    open-pull-requests-limit: 5
    groups:
      # Group all @typescript-eslint/* updates together
      ts-eslint:
        patterns:
          - '@typescript-eslint/*'
      # Group other updates by type
      npm-minor-patch:
        update-types:
          - 'minor'
          - 'patch'
      npm-majors:
        update-types:
          - 'major'

  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: 'Europe/Paris'
    open-pull-requests-limit: 5
    groups:
      rust-minor-patch:
        update-types:
          - 'minor'
          - 'patch'
      rust-majors:
        update-types:
          - 'major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: 'Europe/Paris'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
      include: 'scope'
    groups:
      gha-minor-patch:
        update-types:
          - 'minor'
          - 'patch'
      gha-majors:
        update-types:
          - 'major'
