blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://forge.nardol.ovh/Nardol/instances-finder/src/branch/main/SECURITY.md
    about: Please read our Security Policy for how to report vulnerabilities privately.
