name: release

on:
  push:
    tags: ['v*']
  release:
    types: [created, published]

permissions:
  contents: write

jobs:
  linux-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: Install system deps (Tauri)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev \
            libayatana-appindicator3-dev librsvg2-dev libsoup2.4-dev \
            libjavascriptcoregtk-4.0-dev
      - name: Install JS deps
        run: npm ci || npm install
      - name: Build xtask (release)
        run: cargo build --manifest-path xtask/Cargo.toml --release
      - name: Build AppImage (xtask)
        run: ./xtask/target/release/xtask build appimage
      - name: Build Debian package (xtask)
        run: ./xtask/target/release/xtask build deb
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: |
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/deb/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-nsis:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: Install JS deps
        run: npm ci || npm install
      - name: Build xtask (release)
        run: cargo build --manifest-path xtask/Cargo.toml --release
      - name: Build NSIS installer (xtask)
        run: .\\xtask\\target\\release\\xtask.exe build win-nsis
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: |
            src-tauri/target/release/bundle/nsis/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
