name: release

on:
  push:
    tags: ['v*']
  release:
    types: [created, published]

permissions:
  contents: write

jobs:
  linux-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: Install system deps (Tauri)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev \
            libayatana-appindicator3-dev librsvg2-dev libsoup2.4-dev \
            libjavascriptcoregtk-4.0-dev
      - name: Install JS deps
        run: npm ci || npm install
      - name: Build xtask (release)
        run: cargo build --manifest-path xtask/Cargo.toml --release
      - name: Build AppImage (xtask)
        run: ./xtask/target/release/xtask build appimage
      - name: Build Debian package (xtask)
        run: ./xtask/target/release/xtask build deb
      - name: Determine version (tag)
        shell: bash
        run: |
          ver="${{ github.ref_name }}"
          if [[ -z "$ver" ]]; then ver="${{ github.event.release.tag_name }}"; fi
          echo "VERSION=$ver" >> "$GITHUB_ENV"
      - name: Read release notes template
        id: notes
        shell: bash
        run: |
          sed "s/<VERSION>/${VERSION}/g" .github/release-notes.md > notes.txt
          echo "body<<EOF" >> "$GITHUB_OUTPUT"
          cat notes.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          body: ${{ steps.notes.outputs.body }}
          files: |
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/deb/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-nsis:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: Install JS deps
        run: npm ci || npm install
      - name: Build xtask (release)
        run: cargo build --manifest-path xtask/Cargo.toml --release
      - name: Build NSIS installer (xtask)
        run: .\\xtask\\target\\release\\xtask.exe build win-nsis
      - name: Determine version (tag)
        shell: bash
        run: |
          ver="${{ github.ref_name }}"
          if [[ -z "$ver" ]]; then ver="${{ github.event.release.tag_name }}"; fi
          echo "VERSION=$ver" >> "$GITHUB_ENV"
      - name: Read release notes template
        id: notes_win
        shell: bash
        run: |
          sed "s/<VERSION>/${VERSION}/g" .github/release-notes.md > notes.txt
          echo "body<<EOF" >> "$GITHUB_OUTPUT"
          cat notes.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          body: ${{ steps.notes_win.outputs.body }}
          files: |
            src-tauri/target/release/bundle/nsis/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
